# config.toml

[board]
# parameters defining the game board.
# width and height in grid blocks (integer)
width = 16
height = 24
# grid block size in screen pts (float):
cell_size = 25.0
# initial time between gravity steps (float):
gravity_interval = 0.5
# initial time before piece locks into place (float):
lock_delay = 0.25


[paths]
#paths are relative to executable directory
output_directory = "frames"

[rendering]
texture_width = 3800
texture_height = 1080

# Please don't change these
texture_samples = 1
arc_resolution = 25

[window]
# The size of the monitoring window.
# Currently scaling to 1/2 of texture resolution
width = 1900
height = 540

[osc]
# OSC listening port. UDP only.
rx_port = 8000

[frame_recorder]
# Settings for the frame recorder
# Frame limit of 30000 frames is about 16m40s at 30fps
# Frame limit of 50000 frames is about 13m53s at 60fps
frame_limit = 50000
fps = 30

[style]
# To me this is the best looking line thickness
default_stroke_weight = 10
default_backbone_stroke_weight = 5.1

[speed]
bpm = 120
